# code: language=ansible
---
- name: Register new certificate fingerprint
  ansible.builtin.command: |
    openssl x509 -noout
    -in {{ crt_full_path }}
    -fingerprint -sha1
  register: cmd_new_fingerprint
  changed_when: cmd_new_fingerprint.rc != 0

- name: Register existing certificate fingerprint
  ansible.builtin.command: |
    keytool -list -keystore {{ keystore }} -storepass {{ keystore_password }}
  register: cmd_old_fingerprint
  changed_when: cmd_old_fingerprint.rc != 0

- name: Set vars related to cert fingerprints
  ansible.builtin.set_fact:
    certificate_match: false
    new_fingerprint: "{{ cmd_new_fingerprint.stdout | regex_search(regexp) }}"
    old_fingerprint: "{{ cmd_old_fingerprint.stdout | regex_findall(regexp) }}"
  vars:
    regexp: (?:[0-9a-fA-F]{2}:){19}[0-9a-fA-F]{2}

- name: Set var that certs match if new one was listed in keytool list
  ansible.builtin.set_fact:
    certificate_match: true
  when: new_fingerprint in old_fingerprint
