---
- name: Check if Unifi
  ansible.builtin.stat:
    path: /etc/init.d/unifi
  register: unifi_stat

- ansible.builtin.include_tasks: unifi.yml
  when: (unifi_stat.stat.exists)

- ansible.builtin.include_tasks: certificate-check.yml
  when: (unifi_stat.stat.exists)

- ansible.builtin.include_tasks: common.yml
  when: (unifi_stat.stat.exists) and (not certificate_match)

- name: Check if Unifi-Video
  ansible.builtin.stat:
    path: /etc/init.d/unifi-video
  register: unifi_video_stat

- ansible.builtin.include_tasks: unifi-video.yml
  when: (unifi_video_stat.stat.exists)

- ansible.builtin.include_tasks: certificate-check.yml
  when: (unifi_video_stat.stat.exists)

- ansible.builtin.include_tasks: common.yml
  when: (unifi_video_stat.stat.exists) and (not certificate_match)
