# code: language=ansible
---
- name: Check if Unifi
  ansible.builtin.stat:
    path: /etc/init.d/unifi
  register: unifi_stat

- name: Run tasks from unifi.yml
  ansible.builtin.include_tasks: unifi.yml
  when: (unifi_stat.stat.exists)

- name: Run tasks from certificate-check.yml
  ansible.builtin.include_tasks: certificate-check.yml
  when: (unifi_stat.stat.exists)

- name: Run tasks from common.yml
  ansible.builtin.include_tasks: common.yml
  when: (unifi_stat.stat.exists) and (not certificate_match)

- name: Check if Unifi-Video
  ansible.builtin.stat:
    path: /etc/init.d/unifi-video
  register: unifi_video_stat

- name: Run tasks from unifi-video.yml
  ansible.builtin.include_tasks: unifi-video.yml
  when: (unifi_video_stat.stat.exists)

- name: Run tasks from certificate-check.yml
  ansible.builtin.include_tasks: certificate-check.yml
  when: (unifi_video_stat.stat.exists)

- name: Run tasks from common.yml
  ansible.builtin.include_tasks: common.yml
  when: (unifi_video_stat.stat.exists) and (not certificate_match)
